### ISSUE TITLE
Possibly relax Python version requirement

### ISSUE THREAD

**Issue by bgyori** [dweindl/sbmlmath#1]
Hi @dweindl, this looks like a useful package that we are trying out! It looks like currently the package specifies python>=3.10 as requirement which makes integration difficult since this forces PyPI to look for versions of some dependencies that fit the high version requirement. Is there something that requires >=3.10 in the package currently? If not, would it be possible to reduce the required version to e.g., >=3.8? Thanks!

**Comment by dweindl** [comment]
Hi @bgyori, thanks for showing interest. It don't think there is anything of major importance that requires 3.10 - it was just convenient not having to worry about older versions. I can offer to follow the [NEP 29 policy](https://numpy.org/neps/nep-0029-deprecation_policy.html), this would currently mean >=3.9.

**Comment by dweindl** [comment]
Test suite passed with py39. There is now a py39-compatible release on pypi (https://pypi.org/project/sbmlmath/0.0.3/).
